// .tmp-handoff-v3/pos-admin-panel/project/pages/Orders.jsx
/* ============================================================
   ALPHA POS — Orders (data table page)
   filters + chips · sortable/sticky table · expandable rows ·
   selection + bulk actions · inline actions · states
   ============================================================ */
const { useState, useEffect, useMemo } = React;

/* compact label for an active period chip */
function rangeLabel(r) {
  const PRE = { today: "Today", yesterday: "Yesterday", "7d": "Last 7 days", "30d": "Last 30 days", month: "This month", prevmonth: "Last month", year: "This year" };
  if (r.preset && PRE[r.preset]) return PRE[r.preset];
  const f = (s) => { const d = new Date(s); return Fmt.date(d); };
  if (r.from && r.to) return r.from === r.to ? f(r.from) : f(r.from) + " – " + f(r.to);
  if (r.from) return "From " + f(r.from);
  return "All time";
}

function OrdersPage(props) {
  const [loading, setLoading] = useState(true);
  const [orders, setOrders] = useState(DB.orders);
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [payment, setPayment] = useState("");
  const [range, setRange] = useState({ from: "", to: "", preset: "all" });
  const from = range.from, to = range.to;
  const toast = useToast();

  useEffect(() => {
    setLoading(true);
    const t = setTimeout(() => setLoading(false), 600);
    return () => clearTimeout(t);
  }, [props.dateRange]);

  const filtered = useMemo(() => orders.filter((o) => {
    if (q && !("#" + o.id).includes(q.replace("#", "")) && !String(o.id).includes(q)) return false;
    if (status && o.status !== status) return false;
    if (payment && o.payment !== payment) return false;
    if (from && new Date(o.at) < new Date(from + "T00:00")) return false;
    if (to && new Date(o.at) > new Date(to + "T23:59:59")) return false;
    return true;
  }), [orders, q, status, payment, from, to]);

  const markPaid = (ids) => {
    setOrders((os) => os.map((o) => ids.includes(o.id) ? Object.assign({}, o, { payment: "PAID" }) : o));
    toast({ tone: "success", title: ids.length > 1 ? ids.length + " orders marked paid" : "Order #" + ids[0] + " marked paid" });
  };
  const cancelOrders = (ids) => {
    setOrders((os) => os.map((o) => ids.includes(o.id) ? Object.assign({}, o, { status: "CANCELLED" }) : o));
    toast({ tone: "error", title: ids.length > 1 ? ids.length + " orders cancelled" : "Order #" + ids[0] + " cancelled" });
  };

  const activeFilters = [
    q && { k: "q", label: "Search", val: q, clear: () => setQ("") },
    status && { k: "s", label: "Status", val: status, clear: () => setStatus("") },
    payment && { k: "p", label: "Payment", val: payment, clear: () => setPayment("") },
    (from || to) && { k: "d", label: "Period", val: rangeLabel(range), clear: () => setRange({ from: "", to: "", preset: "all" }) },
  ].filter(Boolean);
  const clearAll = () => { setQ(""); setStatus(""); setPayment(""); setRange({ from: "", to: "", preset: "all" }); };

  const columns = [
    { key: "id", label: "Order", sortable: true, render: (o) => <span className="cell-strong mono">#{o.id}</span> },
    { key: "type", label: "Type", render: (o) => <Badge tone={o.type === "DELIVERY" ? "info" : o.type === "PICKUP" ? "primary" : "neutral"}>{o.type}</Badge> },
    { key: "info", label: "Info", render: (o) => <span className="cell-muted">{o.info}</span> },
    { key: "status", label: "Status", sortable: true, render: (o) => <StatusBadge value={o.status} dot /> },
    { key: "payment", label: "Payment", render: (o) => <StatusBadge value={o.payment} /> },
    { key: "total", label: "Total", sortable: true, align: "right", render: (o) => <span className="mono cell-strong">{Fmt.money(o.total)}</span> },
    { key: "items", label: "Items", align: "right", render: (o) => <span className="mono cell-muted">{o.items}</span> },
    { key: "at", label: "Date", sortable: true, align: "right", sortValue: (o) => new Date(o.at).getTime(), render: (o) => <span className="mono cell-muted nowrap">{Fmt.dateTime(o.at)}</span> },
  ];

  const renderExpand = (o) => (
    <div className="row" style={{ gap: "var(--sp-5)", alignItems: "flex-start", flexWrap: "wrap" }}>
      <div style={{ flex: "2 1 380px", minWidth: 0 }}>
        <div className="kpi__label" style={{ marginBottom: 10 }}>Order items</div>
        <table className="dtable" style={{ background: "var(--surface)", borderRadius: 10, border: "1px solid var(--border)", overflow: "hidden" }}>
          <thead><tr><th>Product</th><th className="num">Qty</th><th className="num">Price</th><th className="num">Subtotal</th></tr></thead>
          <tbody>
            {o.lines.map((l, i) => (
              <tr key={i}>
                <td className="cell-strong">{l.name}</td>
                <td className="num mono">{l.qty}</td>
                <td className="num mono cell-muted">{Fmt.money(l.price)}</td>
                <td className="num mono cell-strong">{Fmt.money(l.price * l.qty)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {o.payment === "PAID" && (
        <div style={{ flex: "1 1 240px", minWidth: 0 }}>
          <PaymentBreakdown methods={o.methods || [{ type: "Cash", amount: o.total }]} total={o.total} />
        </div>
      )}
    </div>
  );

  const rowActions = (o) => (
    <React.Fragment>
      {o.payment === "UNPAID" && o.status !== "CANCELLED" && <IconAction icon="dollar" tone="success" title="Mark paid" onClick={(e) => { e.stopPropagation(); markPaid([o.id]); }} />}
      {(o.status === "PREPARING" || o.status === "READY") && <IconAction icon="close" tone="danger" title="Cancel order" onClick={(e) => { e.stopPropagation(); cancelOrders([o.id]); }} />}
      <IconAction icon="more" title="More" onClick={(e) => e.stopPropagation()} />
    </React.Fragment>
  );

  const bulkActions = (rows, clear) => {
    const ids = rows.map((r) => r.id);
    return (
      <React.Fragment>
        <Button variant="secondary" size="sm" icon="dollar" onClick={() => { markPaid(ids); clear(); }}>Mark paid</Button>
        <Button variant="danger-soft" size="sm" icon="close" onClick={() => { cancelOrders(ids); clear(); }}>Cancel</Button>
        <Button variant="secondary" size="sm" icon="download" onClick={() => { toast({ tone: "info", title: "Exporting " + ids.length + " orders…" }); clear(); }}>Export</Button>
      </React.Fragment>
    );
  };

  return (
    <div className="page">
      <PageHeader title="Orders" subtitle="Track, settle and reconcile every order"
        actions={<Button variant="primary" icon="download">Export to 1C</Button>} />

      <div className="grid cols-4" style={{ marginBottom: "var(--sp-5)" }}>
        {DB.ordersKpis.map((k) => loading ? <KpiSkel key={k.key} /> : <Kpi key={k.key} data={k} />)}
      </div>

      {!loading && <OrdersInsights orders={DB.orders} status={status} payment={payment} onStatus={setStatus} onPayment={setPayment} />}

      <Card>
        <div className="toolbar">
          <div className="grow" style={{ maxWidth: 280 }}>
            <Input icon="search" placeholder="Search orders…" value={q} onChange={(e) => setQ(e.target.value)} />
          </div>
          <div style={{ width: 170 }}><Select icon="filter" placeholder="All statuses" value={status} onChange={setStatus} options={["PREPARING", "READY", "COMPLETED", "CANCELLED"]} /></div>
          <div style={{ width: 170 }}><Select placeholder="All payments" value={payment} onChange={setPayment} options={["PAID", "UNPAID"]} /></div>
          <div style={{ marginLeft: "auto" }}>
            <DateRangePicker value={range} onChange={setRange} align="right" placeholder="All time" />
          </div>
        </div>

        {activeFilters.length > 0 && (
          <div className="toolbar" style={{ paddingTop: 0 }}>
            <div className="chips">
              <span className="tertiary" style={{ fontSize: 13, marginRight: 2 }}>Filters:</span>
              {activeFilters.map((f) => (
                <span key={f.k} className="chip"><span>{f.label}: <b>{f.val}</b></span><span className="chip__x" onClick={f.clear}><Icon name="close" size={13} /></span></span>
              ))}
              <button className="chip--clear" onClick={clearAll}>Clear all</button>
            </div>
          </div>
        )}
        <div className="card__divider" />

        <DataTable
          columns={columns}
          rows={filtered}
          getRowId={(o) => o.id}
          loading={loading}
          selectable
          renderExpand={renderExpand}
          rowActions={rowActions}
          bulkActions={bulkActions}
          initialSort={{ key: "id", dir: "desc" }}
          emptyState={<StateFill icon="receipt" title="No orders match your filters"
            sub="Adjust the search, status or date range to see results."
            action={<div style={{ marginTop: 12 }}><Button variant="secondary" onClick={clearAll}>Clear filters</Button></div>} />}
        />
      </Card>
    </div>
  );
}

/* ---- Interactive insights strip: clickable status distribution + payment + hourly ---- */
function OrdersInsights(props) {
  const orders = props.orders;
  const STATUSES = [
    { key: "PREPARING", label: "Preparing", color: "var(--warning)", tone: "warning" },
    { key: "READY", label: "Ready", color: "var(--success)", tone: "success" },
    { key: "COMPLETED", label: "Completed", color: "var(--primary)", tone: "primary" },
    { key: "CANCELLED", label: "Cancelled", color: "var(--error)", tone: "error" },
  ];
  const counts = {}; STATUSES.forEach((s) => counts[s.key] = 0);
  let paid = 0, unpaid = 0, revenue = 0;
  orders.forEach((o) => {
    if (counts[o.status] !== undefined) counts[o.status] += 1;
    if (o.payment === "PAID") { paid += 1; revenue += o.total; } else unpaid += 1;
  });
  const total = orders.length || 1;
  const paidPct = Math.round(paid / total * 100);

  // hourly distribution
  const byHour = {};
  orders.forEach((o) => { const h = new Date(o.at).getHours(); byHour[h] = (byHour[h] || 0) + 1; });
  const hours = []; for (let h = 11; h <= 22; h++) hours.push(byHour[h] || 0);

  return (
    <div className="grid" style={{ gridTemplateColumns: "1.5fr 1fr 1fr", marginBottom: "var(--sp-5)", gap: "var(--sp-5)" }}>
      {/* status distribution — clickable to filter */}
      <Card style={{ padding: "var(--sp-5)" }}>
        <div className="row between" style={{ marginBottom: 14 }}>
          <span className="kpi__label">Status distribution</span>
          <span className="tertiary" style={{ fontSize: 12 }}>click to filter</span>
        </div>
        <div className="distbar">
          {STATUSES.map((s) => {
            const pct = counts[s.key] / total * 100;
            if (pct === 0) return null;
            const active = props.status === s.key;
            return (
              <div key={s.key} className={cx("distbar__seg", props.status && !active && "is-dim")}
                style={{ width: pct + "%", background: s.color }}
                title={s.label + ": " + counts[s.key]}
                onClick={() => props.onStatus(active ? "" : s.key)} />
            );
          })}
        </div>
        <div className="row wrap" style={{ gap: 14, marginTop: 14 }}>
          {STATUSES.map((s) => {
            const active = props.status === s.key;
            return (
              <button key={s.key} className={cx("distlegend", active && "is-active")} onClick={() => props.onStatus(active ? "" : s.key)}>
                <span className="legend-swatch" style={{ background: s.color }} />
                <span>{s.label}</span>
                <b className="mono">{counts[s.key]}</b>
              </button>
            );
          })}
        </div>
      </Card>

      {/* payment split — ring */}
      <Card style={{ padding: "var(--sp-5)" }}>
        <div className="kpi__label" style={{ marginBottom: 8 }}>Payment status</div>
        <div className="row" style={{ gap: 16, alignItems: "center" }}>
          <ProgressRing value={paidPct} color="var(--success)" size={84} />
          <div style={{ flex: 1, minWidth: 0 }}>
            <button className={cx("distlegend", props.payment === "PAID" && "is-active")} style={{ width: "100%", justifyContent: "flex-start" }} onClick={() => props.onPayment(props.payment === "PAID" ? "" : "PAID")}>
              <span className="legend-swatch" style={{ background: "var(--success)" }} /><span>Paid</span><b className="mono" style={{ marginLeft: "auto" }}>{paid}</b>
            </button>
            <button className={cx("distlegend", props.payment === "UNPAID" && "is-active")} style={{ width: "100%", justifyContent: "flex-start", marginTop: 4 }} onClick={() => props.onPayment(props.payment === "UNPAID" ? "" : "UNPAID")}>
              <span className="legend-swatch" style={{ background: "var(--error)" }} /><span>Unpaid</span><b className="mono" style={{ marginLeft: "auto" }}>{unpaid}</b>
            </button>
          </div>
        </div>
      </Card>

      {/* hourly mini bars */}
      <Card style={{ padding: "var(--sp-5)" }}>
        <div className="row between" style={{ marginBottom: 8 }}>
          <span className="kpi__label">Orders by hour</span>
          <span className="badge t-neutral">11:00–22:00</span>
        </div>
        <MiniBars data={hours} labels={["11","","13","","15","","17","","19","","21",""]} />
      </Card>
    </div>
  );
}

/* tiny inline bar chart */
function MiniBars(props) {
  const shown = window.useShown ? useShown(80) : true;
  const data = props.data, max = Math.max.apply(null, data) || 1;
  const peak = data.indexOf(max);
  return (
    <div style={{ display: "flex", alignItems: "flex-end", gap: 4, height: 64 }}>
      {data.map((v, i) => (
        <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, height: "100%", justifyContent: "flex-end" }} title={(11 + i) + ":00 · " + v + " orders"}>
          <div style={{ width: "100%", height: (shown ? (v / max) * 46 : 0) + "px", minHeight: 2, borderRadius: 3, background: i === peak ? "var(--chart-revenue)" : "var(--c4)", transition: "height .5s cubic-bezier(.2,.8,.2,1) " + (i * 0.025) + "s" }} />
          <span style={{ fontSize: 9, color: "var(--text-tertiary)", fontFamily: "var(--font-mono)" }}>{props.labels[i]}</span>
        </div>
      ))}
    </div>
  );
}

/* Payment breakdown — splits a (possibly mixed) payment into method rows with amounts */
function PaymentBreakdown(props) {
  const methods = props.methods || [];
  const total = props.total || methods.reduce((a, m) => a + m.amount, 0);
  const TONE = { Cash: "var(--c2)", Uzcard: "var(--c1)", Humo: "var(--c4)", Payme: "var(--c3)", Click: "var(--c5)", Card: "var(--c1)" };
  const mixed = methods.length > 1;
  return (
    <div className="paybreak">
      <div className="row between" style={{ marginBottom: 10 }}>
        <span className="kpi__label">Payment {mixed && <span className="badge t-primary" style={{ marginLeft: 6 }}>Mixed · {methods.length}</span>}</span>
        <span className="mono cell-strong" style={{ fontSize: 13 }}>{Fmt.money(total)}</span>
      </div>
      <div className="paybreak__bar">
        {methods.map((m, i) => (
          <div key={i} className="paybreak__seg" style={{ width: (m.amount / total * 100) + "%", background: TONE[m.type] || "var(--c5)" }} title={m.type} />
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6, marginTop: 12 }}>
        {methods.map((m, i) => (
          <div key={i} className="row between">
            <span className="legend-item"><span className="legend-swatch" style={{ background: TONE[m.type] || "var(--c5)" }} />{m.type}</span>
            <span className="row" style={{ gap: 8 }}>
              <span className="mono cell-strong" style={{ fontSize: 13 }}>{Fmt.money(m.amount)}</span>
              <span className="tertiary mono" style={{ fontSize: 11, width: 34, textAlign: "right" }}>{Math.round(m.amount / total * 100)}%</span>
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

Object.assign(window, { OrdersPage, OrdersInsights, MiniBars, PaymentBreakdown });

// src/pages/orders/index.vue
<script setup lang="ts">
/* ============================================================
   ALPHA POS — Orders page
   1:1 port of .tmp-alpha-design/alpha-design-source/Orders.jsx
   filters + chips · sortable/sticky table · expandable rows ·
   selection + bulk actions · inline actions · states
   All existing axios calls / refs / computed / watchers preserved.
   ============================================================ */
import { ORDER_STATUS_COLOR as statusColor } from '@/constants/statusColors'
import axios from '@/plugins/axios'
import Badge from '@/components/design/Badge.vue'
import Button from '@/components/design/Button.vue'
import Checkbox from '@/components/design/Checkbox.vue'
import DataTable, { type DataTableColumn } from '@/components/design/DataTable.vue'
import DesignIcon from '@/components/design/DesignIcon.vue'
import IconAction from '@/components/design/IconAction.vue'
import Input from '@/components/design/Input.vue'
import Kpi from '@/components/design/Kpi.vue'
import Modal from '@/components/design/Modal.vue'
import PageHeader from '@/components/design/PageHeader.vue'
import Select from '@/components/design/Select.vue'
import StateFill from '@/components/design/StateFill.vue'

const { t } = useI18n({ useScope: 'global' })
const { notify } = useNotify()
const { formatCurrency, formatDate } = useFormatters()

// ---- state ----
const orders = ref<any[]>([])
const totalOrders = ref(0)
const loading = ref(false)
const stats = ref<any>(null)

const page = ref(1)
const itemsPerPage = ref(10)
const statusFilter = ref<string[]>([])
const paymentFilter = ref<string | undefined>(undefined)
const search = ref('')
const dateFrom = ref('')
const dateTo = ref('')

const expanded = ref<Set<number | string>>(new Set())
const selected = ref<Set<number | string>>(new Set())

const sortKey = ref<string>('id')
const sortDir = ref<'asc' | 'desc'>('desc')

// Per-row + bulk loading state to prevent duplicate POSTs
const actingOnId = ref<number | string | null>(null)
const bulking = ref(false)
const exporting = ref(false)

// Destructive-action confirm dialogs
type ConfirmKind = 'cancel-one' | 'cancel-bulk' | 'pay-one' | 'pay-bulk'
const confirmDialog = ref<{ kind: ConfirmKind, order?: any } | null>(null)
function openConfirm(kind: ConfirmKind, order?: any) {
  confirmDialog.value = { kind, order }
}
function closeConfirm() {
  confirmDialog.value = null
}

const debouncedSearch = useDebounceFn(() => {
  page.value = 1
  loadOrders()
}, 400)

const orderStatuses = ['OPEN', 'PREPARING', 'READY', 'COMPLETED', 'CANCELED']
const paymentStatuses = ['PAID', 'UNPAID']

// Status tone map mirrored from the design bundle
const STATUS_TONE: Record<string, string> = {
  ACTIVE: 'success', COMPLETED: 'success', READY: 'success', PAID: 'success',
  PREPARING: 'warning', PENDING: 'warning', OPEN: 'warning', INACTIVE: 'neutral',
  CANCELLED: 'error', CANCELED: 'error', UNPAID: 'error',
  CASHIER: 'info', USER: 'neutral', MANAGER: 'primary', ADMIN: 'primary',
  HALL: 'neutral', DELIVERY: 'info', PICKUP: 'primary',
}
function tone(v: string | undefined) {
  if (!v) return 'neutral'
  return STATUS_TONE[v] ?? statusColor[v] ?? 'neutral'
}

// ---- load ----
async function loadOrders() {
  loading.value = true
  try {
    const params: any = { page: page.value, per_page: itemsPerPage.value }
    if (statusFilter.value.length)
      params.statuses = statusFilter.value.join(',')
    if (paymentFilter.value)
      params.payment_status = paymentFilter.value
    if (search.value.trim())
      params.search = search.value.trim()
    if (dateFrom.value)
      params.date_from = dateFrom.value
    if (dateTo.value)
      params.date_to = dateTo.value

    const res = await axios.get('/orders', { params })
    const d = res.data?.data

    orders.value = d?.orders ?? []
    totalOrders.value = d?.pagination?.total_orders ?? orders.value.length
  }
  catch {
    notify(t('Failed to load orders'), 'error')
  }
  finally {
    loading.value = false
  }
}

async function loadStats() {
  try {
    const res = await axios.get('/orders/stats')

    stats.value = res.data?.data ?? res.data
  }
  catch { /* ignore */ }
}

onMounted(() => {
  loadOrders()
  loadStats()
})

watch([page, itemsPerPage], loadOrders)
watch([statusFilter, paymentFilter, dateFrom, dateTo], () => {
  page.value = 1
  loadOrders()
})
watch(search, () => debouncedSearch())

// ---- actions ----
async function markPaid(order: any) {
  if (actingOnId.value === order.id) return
  actingOnId.value = order.id
  try {
    await axios.post(`/orders/${order.id}/pay`)
    notify(t('Order marked as paid'))
    await Promise.all([loadOrders(), loadStats()])
  }
  catch (e: any) {
    notify(e?.response?.data?.message ?? t('Error updating order'), 'error')
  }
  finally {
    actingOnId.value = null
  }
}

async function cancelOrder(order: any) {
  if (actingOnId.value === order.id) return
  actingOnId.value = order.id
  try {
    await axios.post(`/orders/${order.id}/cancel`)
    notify(t('Order cancelled'))
    await Promise.all([loadOrders(), loadStats()])
  }
  catch (e: any) {
    notify(e?.response?.data?.message ?? t('Error cancelling order'), 'error')
  }
  finally {
    actingOnId.value = null
  }
}

// Wrappers triggered from confirm dialog
async function confirmCancelOne() {
  const o = confirmDialog.value?.order
  closeConfirm()
  if (o) await cancelOrder(o)
}
async function confirmPayOne() {
  const o = confirmDialog.value?.order
  closeConfirm()
  if (o) await markPaid(o)
}
async function confirmCancelBulk() {
  closeConfirm()
  await bulkCancel()
}
async function confirmPayBulk() {
  closeConfirm()
  await bulkMarkPaid()
}

async function exportOneC() {
  if (!dateFrom.value || !dateTo.value) {
    notify(t('Pick a date range to export'), 'error')
    return
  }
  if (exporting.value) return
  exporting.value = true
  try {
    const res = await axios.get('/exports/1c', {
      params: { from: dateFrom.value, to: dateTo.value },
      responseType: 'blob',
    })

    const url = URL.createObjectURL(new Blob([res.data], { type: 'application/xml' }))
    const a = document.createElement('a')

    a.href = url
    a.download = `orders-${dateFrom.value}-to-${dateTo.value}.xml`
    a.click()
    URL.revokeObjectURL(url)
    notify(t('Export downloaded'))
  }
  catch (e: any) {
    notify(e?.response?.data?.message ?? t('Export failed'), 'error')
  }
  finally {
    exporting.value = false
  }
}

// ---- bulk + selection ----
async function bulkMarkPaid() {
  if (bulking.value) return
  bulking.value = true
  try {
    const ids = [...selected.value]
    for (const id of ids) {
      const o = orders.value.find((x: any) => x.id === id)
      if (o) await markPaid(o)
    }
    selected.value = new Set()
  }
  finally {
    bulking.value = false
  }
}
async function bulkCancel() {
  if (bulking.value) return
  bulking.value = true
  try {
    const ids = [...selected.value]
    for (const id of ids) {
      const o = orders.value.find((x: any) => x.id === id)
      if (o) await cancelOrder(o)
    }
    selected.value = new Set()
  }
  finally {
    bulking.value = false
  }
}

function toggleRow(id: number | string) {
  if (expanded.value.has(id)) expanded.value.delete(id)
  else expanded.value.add(id)
  expanded.value = new Set(expanded.value)
}
function toggleSelect(id: number | string, ev?: Event) {
  if (ev) ev.stopPropagation()
  if (selected.value.has(id)) selected.value.delete(id)
  else selected.value.add(id)
  selected.value = new Set(selected.value)
}
const allSelected = computed(() => orders.value.length > 0 && orders.value.every((o: any) => selected.value.has(o.id)))
const someSelected = computed(() => selected.value.size > 0 && !allSelected.value)
function toggleSelectAll() {
  if (allSelected.value) selected.value = new Set()
  else selected.value = new Set(orders.value.map((o: any) => o.id))
}

// ---- sort ----
function setSort(key: string) {
  if (sortKey.value === key) sortDir.value = sortDir.value === 'asc' ? 'desc' : 'asc'
  else { sortKey.value = key; sortDir.value = 'asc' }
}
const sortedOrders = computed(() => {
  const arr = [...orders.value]
  const k = sortKey.value
  const dir = sortDir.value === 'asc' ? 1 : -1
  arr.sort((a: any, b: any) => {
    let av: any, bv: any
    if (k === 'id') { av = a.display_id ?? a.id; bv = b.display_id ?? b.id }
    else if (k === 'total') { av = Number(a.total_amount) || 0; bv = Number(b.total_amount) || 0 }
    else if (k === 'at') { av = new Date(a.created_at).getTime(); bv = new Date(b.created_at).getTime() }
    else if (k === 'status') { av = a.status; bv = b.status }
    else { av = (a as any)[k]; bv = (b as any)[k] }
    if (av == null) return 1
    if (bv == null) return -1
    if (av < bv) return -1 * dir
    if (av > bv) return 1 * dir
    return 0
  })
  return arr
})

// ---- pagination ----
const totalPages = computed(() => Math.max(1, Math.ceil(totalOrders.value / itemsPerPage.value)))
const pageList = computed(() => {
  const tp = totalPages.value
  const p = page.value
  const list: (number | string)[] = []
  const push = (x: number | string) => list.push(x)
  if (tp <= 7) { for (let i = 1; i <= tp; i++) push(i); return list }
  push(1)
  if (p > 3) push('…')
  const start = Math.max(2, p - 1)
  const end = Math.min(tp - 1, p + 1)
  for (let i = start; i <= end; i++) push(i)
  if (p < tp - 2) push('…')
  push(tp)
  return list
})
const rangeStart = computed(() => totalOrders.value === 0 ? 0 : (page.value - 1) * itemsPerPage.value + 1)
const rangeEnd = computed(() => Math.min(page.value * itemsPerPage.value, totalOrders.value))

// ---- filter chips ----
const hasFilters = computed(() =>
  !!(search.value || statusFilter.value.length || paymentFilter.value || dateFrom.value || dateTo.value),
)
function clearAll() {
  search.value = ''
  statusFilter.value = []
  paymentFilter.value = undefined
  dateFrom.value = ''
  dateTo.value = ''
}

// ---- formatters ----
function infoOf(o: any) {
  const ph = o.phone_number && o.phone_number !== '+998' ? o.phone_number : null
  return ph || o.description || '—'
}
function itemsOf(o: any) {
  return o.items_count ?? o.items?.length ?? '—'
}

// ---- DataTable columns ----
const columns = computed<DataTableColumn<any>[]>(() => [
  { key: 'id', label: '#', sortable: true },
  { key: 'type', label: t('Type') },
  { key: 'info', label: t('Info') },
  { key: 'status', label: t('Status'), sortable: true },
  { key: 'payment', label: t('Payment') },
  { key: 'total', label: t('Total'), sortable: true, align: 'right' },
  { key: 'items', label: t('Items'), align: 'right' },
  { key: 'at', label: t('Date'), sortable: true, align: 'right' },
])

// Bridge our internal sort state to DataTable's sort prop
const dtSort = computed(() => ({
  key: sortKey.value === 'id'
    ? 'id'
    : sortKey.value === 'total'
      ? 'total'
      : sortKey.value === 'at' ? 'at' : sortKey.value === 'status' ? 'status' : sortKey.value,
  dir: sortDir.value,
}))
function onDtSort(s: { key: string | null, dir: 'asc' | 'desc' }) {
  if (!s.key) return
  sortKey.value = s.key
  sortDir.value = s.dir
}

// Selection sync with DataTable
function onDtSelection(next: Set<string | number>) {
  selected.value = next
}

// Pagination passthrough
const dtPagination = computed(() => ({
  page: page.value,
  perPage: itemsPerPage.value,
  total: totalOrders.value,
  onPage: (p: number) => { page.value = p },
  onPerPage: (n: number) => { itemsPerPage.value = n; page.value = 1 },
}))

const noResultsMsg = computed(() => t('No orders match your filters'))
const noResultsSub = computed(() => t('Adjust the search, status or date range to see results.'))
</script>

<template>
  <div class="page">
    <!-- Page header -->
    <PageHeader
      :title="t('Orders')"
      :subtitle="t('Track, settle and reconcile every order')"
    >
      <template #actions>
        <Button
          variant="primary"
          icon="download"
          :loading="exporting"
          :disabled="!dateFrom || !dateTo || exporting"
          @click="exportOneC"
        >
          {{ t('Export to 1C') }}
        </Button>
      </template>
    </PageHeader>

    <!-- KPI strip -->
    <div class="grid cols-4" style="margin-bottom: var(--sp-5);">
      <Kpi
        :data="{
          label: t('Total'),
          icon: 'receipt',
          tone: 'primary',
          value: stats ? (stats.total_orders ?? 0) : null,
        }"
      />
      <Kpi
        :data="{
          label: t('Preparing'),
          icon: 'clock',
          tone: 'warning',
          value: stats ? (stats.preparing_orders ?? 0) : null,
        }"
      />
      <Kpi
        :data="{
          label: t('Ready'),
          icon: 'check',
          tone: 'success',
          value: stats ? (stats.ready_orders ?? 0) : null,
        }"
      />
      <Kpi
        :data="{
          label: t('Revenue'),
          icon: 'dollar',
          tone: 'info',
          money: true,
          value: stats ? (stats.total_revenue ?? 0) : null,
        }"
      />
    </div>

    <!-- Main table card -->
    <div class="card">
      <!-- Toolbar -->
      <div class="toolbar">
        <div class="grow" style="max-width: 280px;">
          <Input
            v-model="search"
            icon="search"
            :placeholder="t('Search orders...')"
            :aria-label="t('Search orders')"
          />
        </div>

        <div style="width: 200px;">
          <Select
            :model-value="statusFilter[0] ?? ''"
            icon="filter"
            :placeholder="t('Filter by Status')"
            :options="orderStatuses.map(s => ({ value: s, label: t(s) }))"
            @update:model-value="(v: string) => statusFilter = v ? [v] : []"
          />
        </div>

        <div style="width: 180px;">
          <Select
            :model-value="paymentFilter ?? ''"
            :placeholder="t('Payment Status')"
            :options="paymentStatuses.map(p => ({ value: p, label: t(p) }))"
            @update:model-value="(v: string) => paymentFilter = v ? v : undefined"
          />
        </div>

        <div class="row" style="gap: 8px; margin-left: auto;">
          <div class="control control--sm" style="width: 160px;">
            <input v-model="dateFrom" type="date" :aria-label="t('From')">
          </div>
          <span class="tertiary">→</span>
          <div class="control control--sm" style="width: 160px;">
            <input v-model="dateTo" type="date" :aria-label="t('To')">
          </div>
        </div>
      </div>

      <!-- Active filter chips -->
      <div v-if="hasFilters" class="toolbar" style="padding-top: 0;">
        <div class="chips">
          <span class="tertiary" style="font-size: 13px; margin-right: 2px;">{{ t('Filters') }}:</span>

          <span v-if="search" class="chip">
            <span>{{ t('Search') }}: <b>{{ search }}</b></span>
            <span class="chip__x" @click="search = ''">
              <DesignIcon name="close" :size="13" />
            </span>
          </span>

          <span v-for="s in statusFilter" :key="s" class="chip">
            <span>{{ t('Status') }}: <b>{{ t(s) }}</b></span>
            <span class="chip__x" @click="statusFilter = statusFilter.filter(x => x !== s)">
              <DesignIcon name="close" :size="13" />
            </span>
          </span>

          <span v-if="paymentFilter" class="chip">
            <span>{{ t('Payment') }}: <b>{{ t(paymentFilter) }}</b></span>
            <span class="chip__x" @click="paymentFilter = undefined">
              <DesignIcon name="close" :size="13" />
            </span>
          </span>

          <span v-if="dateFrom" class="chip">
            <span>{{ t('From') }}: <b>{{ dateFrom }}</b></span>
            <span class="chip__x" @click="dateFrom = ''">
              <DesignIcon name="close" :size="13" />
            </span>
          </span>

          <span v-if="dateTo" class="chip">
            <span>{{ t('To') }}: <b>{{ dateTo }}</b></span>
            <span class="chip__x" @click="dateTo = ''">
              <DesignIcon name="close" :size="13" />
            </span>
          </span>

          <button class="chip--clear" @click="clearAll">
            {{ t('Clear all') }}
          </button>
        </div>
      </div>

      <div class="card__divider" />

      <!-- DataTable: sortable / selectable / expandable, server-paginated -->
      <DataTable
        :columns="columns"
        :rows="sortedOrders"
        row-key="id"
        :loading="loading"
        selectable
        expandable
        :sort="dtSort"
        :selection="selected"
        :pagination="dtPagination"
        :per-page-options="[10, 25, 50, 100]"
        @sort="onDtSort"
        @update:selection="onDtSelection"
        @row-click="(o: any) => toggleRow(o.id)"
      >
        <!-- Order # -->
        <template #cell.id="{ row: o }">
          <span class="cell-strong mono">#{{ o.display_id ?? o.id }}</span>
        </template>

        <!-- Type -->
        <template #cell.type="{ row: o }">
          <Badge :tone="(tone(o.order_type) as any)">
            {{ t(o.order_type) }}
          </Badge>
        </template>

        <!-- Info -->
        <template #cell.info="{ row: o }">
          <span class="cell-muted">{{ infoOf(o) }}</span>
        </template>

        <!-- Status with dot -->
        <template #cell.status="{ row: o }">
          <Badge :tone="(tone(o.status) as any)" dot>
            {{ t(o.status) }}
          </Badge>
        </template>

        <!-- Payment -->
        <template #cell.payment="{ row: o }">
          <Badge :tone="o.is_paid ? 'success' : 'error'">
            {{ o.is_paid ? t('PAID') : t('UNPAID') }}
          </Badge>
        </template>

        <!-- Total -->
        <template #cell.total="{ row: o }">
          <span class="mono cell-strong">{{ formatCurrency(o.total_amount ?? 0) }}</span>
        </template>

        <!-- Items -->
        <template #cell.items="{ row: o }">
          <span class="mono cell-muted">{{ itemsOf(o) }}</span>
        </template>

        <!-- Date -->
        <template #cell.at="{ row: o }">
          <span class="mono cell-muted nowrap">{{ formatDate(o.created_at) }}</span>
        </template>

        <!-- Bulk actions -->
        <template #bulk-actions>
          <Button
            variant="secondary"
            size="sm"
            icon="dollar"
            :loading="bulking"
            :disabled="bulking"
            @click="openConfirm('pay-bulk')"
          >
            {{ t('Mark paid') }}
          </Button>
          <Button
            variant="danger-soft"
            size="sm"
            icon="close"
            :loading="bulking"
            :disabled="bulking"
            @click="openConfirm('cancel-bulk')"
          >
            {{ t('Cancel') }}
          </Button>
        </template>

        <!-- Inline row actions -->
        <template #row-actions="{ row: o }">
          <IconAction
            v-if="!o.is_paid && o.status !== 'CANCELED'"
            icon="dollar"
            tone="success"
            :title="t('Pay')"
            :disabled="actingOnId === o.id"
            @click="openConfirm('pay-one', o)"
          />
          <IconAction
            v-if="o.status !== 'CANCELED' && o.status !== 'COMPLETED'"
            icon="close"
            tone="danger"
            :title="t('Cancel')"
            :disabled="actingOnId === o.id"
            @click="openConfirm('cancel-one', o)"
          />
          <IconAction icon="more" :title="t('More')" />
        </template>

        <!-- Expanded row: order items -->
        <template #expanded="{ row: o }">
          <div class="kpi__label" style="margin-bottom: 10px;">
            {{ t('Order Items') }}
          </div>
          <div class="tablewrap">
            <table
              class="dtable"
              style="background: var(--surface); border-radius: 10px; border: 1px solid var(--border); overflow: hidden;"
            >
              <thead>
                <tr>
                  <th>{{ t('Product') }}</th>
                  <th class="num">
                    {{ t('Qty') }}
                  </th>
                  <th class="num">
                    {{ t('Price') }}
                  </th>
                  <th class="num">
                    {{ t('Subtotal') }}
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(li, i) in ((o.items ?? []) as any[])" :key="i">
                  <td class="cell-strong">
                    {{ li.product__name ?? '—' }}
                  </td>
                  <td class="num mono">
                    {{ li.quantity ?? '—' }}
                  </td>
                  <td class="num mono cell-muted">
                    {{ formatCurrency(li.price ?? 0) }}
                  </td>
                  <td class="num mono cell-strong">
                    {{ formatCurrency((Number(li.price) || 0) * (li.quantity ?? 1)) }}
                  </td>
                </tr>
                <tr v-if="!(o.items?.length)">
                  <td colspan="4" class="center cell-muted">
                    {{ t('No items') }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Empty state -->
        <template #empty>
          <StateFill
            icon="receipt"
            :title="noResultsMsg"
            :sub="noResultsSub"
          >
            <div v-if="hasFilters" style="margin-top: 12px;">
              <Button variant="secondary" @click="clearAll">
                {{ t('Clear filters') }}
              </Button>
            </div>
          </StateFill>
        </template>
      </DataTable>
    </div>

    <!-- Confirm action modal (cancel / mark paid, single or bulk) -->
    <Modal
      :open="confirmDialog !== null"
      :width="440"
      :title="confirmDialog?.kind === 'cancel-one' ? t('Cancel this order?')
        : confirmDialog?.kind === 'cancel-bulk' ? t('Cancel selected orders?')
          : confirmDialog?.kind === 'pay-one' ? t('Mark this order as paid?')
            : t('Mark selected orders as paid?')"
      :subtitle="(confirmDialog?.kind === 'cancel-one' || confirmDialog?.kind === 'cancel-bulk')
        ? t('This action cannot be undone')
        : t('Payment status will change immediately.')"
      @close="closeConfirm"
    >
      <div v-if="confirmDialog" class="row" style="gap:14px;align-items:flex-start;">
        <div
          class="kpi__icon"
          :class="(confirmDialog.kind === 'cancel-one' || confirmDialog.kind === 'cancel-bulk') ? 't-error' : 't-success'"
          style="width:44px;height:44px;flex:0 0 44px;"
        >
          <DesignIcon name="alert" :size="22" />
        </div>
        <div>
          <p v-if="confirmDialog.order" style="margin:0;font-weight:600;">
            #{{ confirmDialog.order.display_id ?? confirmDialog.order.id }}
            · {{ formatCurrency(confirmDialog.order.total_amount ?? 0) }}
          </p>
          <p v-else style="margin:0;font-weight:600;">
            {{ t('{count} selected', { count: selected.size }) }}
          </p>
          <p class="muted" style="margin:6px 0 0;font-size:14px;">
            <template v-if="confirmDialog.kind === 'cancel-one' || confirmDialog.kind === 'cancel-bulk'">
              {{ t('Cancelling may require a refund and impact the customer.') }}
            </template>
            <template v-else>
              {{ t('No refund flow will be triggered.') }}
            </template>
          </p>
        </div>
      </div>

      <template #footer>
        <Button variant="ghost" :disabled="bulking || actingOnId !== null" @click="closeConfirm">
          {{ t('Close') }}
        </Button>
        <Button
          v-if="confirmDialog?.kind === 'cancel-one'"
          variant="danger"
          :loading="actingOnId !== null"
          :disabled="actingOnId !== null"
          @click="confirmCancelOne"
        >
          {{ t('Cancel order') }}
        </Button>
        <Button
          v-else-if="confirmDialog?.kind === 'cancel-bulk'"
          variant="danger"
          :loading="bulking"
          :disabled="bulking"
          @click="confirmCancelBulk"
        >
          {{ t('Cancel orders') }}
        </Button>
        <Button
          v-else-if="confirmDialog?.kind === 'pay-one'"
          variant="primary"
          :loading="actingOnId !== null"
          :disabled="actingOnId !== null"
          @click="confirmPayOne"
        >
          {{ t('Mark paid') }}
        </Button>
        <Button
          v-else
          variant="primary"
          :loading="bulking"
          :disabled="bulking"
          @click="confirmPayBulk"
        >
          {{ t('Mark paid') }}
        </Button>
      </template>
    </Modal>
  </div>
</template>

<style scoped>
/* Layout-only safeguards. All visual styling comes from
   src/styles/design-shell.css (verbatim ported alpha-design-system.css). */
.row {
  display: flex;
  align-items: center;
}
</style>

<route lang="yaml">
meta:
  action: manage
  subject: all
</route>
